// src/components/layout/Header.vue
<template>
  <header :class="['ges-header', { 'ges-header--scrolled': scrolled }]">
    <!-- Main nav -->
    <nav class="ges-nav container">
      <!-- Logo / Brand -->
      <RouterLink to="/" class="ges-brand">
        <img src="/logo.png" alt="GES" class="ges-brand__logo" />
      </RouterLink>

      <!-- Desktop Nav -->
      <div class="ges-nav__links">
        <RouterLink
          v-for="link in navLinks"
          :key="link.path"
          :to="link.path"
          class="ges-nav__link"
          :class="{ 'ges-nav__link--active': route.path === link.path }"
        >
          {{ link.name }}
        </RouterLink>

        <!-- Institutions Dropdown -->
        <div class="ges-dropdown" @mouseenter="dropOpen = true" @mouseleave="dropOpen = false">
          <button class="ges-nav__link ges-dropdown__trigger" :class="{ 'ges-nav__link--active': isInstitutionRoute }">
            INSTITUTIONS
            <svg class="ges-dropdown__arrow" :class="{ 'ges-dropdown__arrow--open': dropOpen }" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
              <polyline points="6 9 12 15 18 9" />
            </svg>
          </button>
          <Transition name="dropdown">
            <div v-if="dropOpen" class="ges-dropdown__menu">
              <a
                v-for="inst in institutions"
                :key="inst.path"
                :href="inst.url"
                class="ges-dropdown__item"
                @click="dropOpen = false"
              >
                <span class="ges-dropdown__item-name">{{ inst.name }}</span>
                <span class="ges-dropdown__item-desc">{{ inst.description }}</span>
              </a>
            </div>
          </Transition>
        </div>

        <!-- About Dropdown -->
        <div class="ges-dropdown" @mouseenter="aboutOpen = true" @mouseleave="aboutOpen = false">
          <button class="ges-nav__link ges-dropdown__trigger" :class="{ 'ges-nav__link--active': isAboutRoute }">
            ABOUT
            <svg class="ges-dropdown__arrow" :class="{ 'ges-dropdown__arrow--open': aboutOpen }" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
              <polyline points="6 9 12 15 18 9" />
            </svg>
          </button>
          <Transition name="dropdown">
            <div v-if="aboutOpen" class="ges-dropdown__menu ges-dropdown__menu--sm">
              <RouterLink to="/about" class="ges-dropdown__item" @click="aboutOpen = false">
                <span class="ges-dropdown__item-name">About Us</span>
                <span class="ges-dropdown__item-desc">Vision, mission &amp; values</span>
              </RouterLink>
              <RouterLink to="/leadership" class="ges-dropdown__item" @click="aboutOpen = false">
                <span class="ges-dropdown__item-name">Leadership</span>
                <span class="ges-dropdown__item-desc">Management committee</span>
              </RouterLink>
              <RouterLink to="/partnerships" class="ges-dropdown__item" @click="aboutOpen = false">
                <span class="ges-dropdown__item-name">Partnerships</span>
                <span class="ges-dropdown__item-desc">Our global partners</span>
              </RouterLink>
            </div>
          </Transition>
        </div>
      </div>

        <!-- CTA Button (desktop) -->
        <div class="ges-nav__cta">
          <RouterLink to="/about" class="ges-nav__donate" aria-label="Get in touch">
            <span class="ges-nav__donate-text">Get in Touch</span>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>
          </RouterLink>
        </div>

      <!-- Mobile Hamburger -->
      <button class="ges-hamburger" @click="mobileOpen = !mobileOpen" aria-label="Toggle menu">
        <span :class="['ges-hamburger__bar', { 'ges-hamburger__bar--open-1': mobileOpen }]"></span>
        <span :class="['ges-hamburger__bar', { 'ges-hamburger__bar--open-2': mobileOpen }]"></span>
        <span :class="['ges-hamburger__bar', { 'ges-hamburger__bar--open-3': mobileOpen }]"></span>
      </button>
    </nav>

    <!-- Mobile Menu -->
    <Transition name="mobile-menu">
      <div v-if="mobileOpen" class="ges-mobile-menu">
        <RouterLink
          v-for="link in navLinks"
          :key="link.path"
          :to="link.path"
          class="ges-mobile-menu__link"
          @click="mobileOpen = false"
        >
          {{ link.name }}
        </RouterLink>
        <RouterLink to="/about" class="ges-mobile-menu__link" @click="mobileOpen = false">About Us</RouterLink>
        <RouterLink to="/leadership" class="ges-mobile-menu__link" @click="mobileOpen = false">Leadership</RouterLink>
        <RouterLink to="/partnerships" class="ges-mobile-menu__link" @click="mobileOpen = false">Partnerships</RouterLink>
        <div class="ges-mobile-menu__divider"></div>
        <p class="ges-mobile-menu__section">Institutions</p>
        <a
          v-for="inst in institutions"
          :key="inst.path"
          :href="inst.url"
          class="ges-mobile-menu__link ges-mobile-menu__link--sub"
          @click="mobileOpen = false"
        >
          {{ inst.shortName }}
        </a>
        <RouterLink to="/about" class="ges-mobile-menu__cta" @click="mobileOpen = false">Get in Touch</RouterLink>
      </div>
    </Transition>
  </header>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useRoute } from 'vue-router';
import { useScroll } from '@vueuse/core';

const route = useRoute();
const { y } = useScroll(window);
const scrolled = computed(() => y.value > 40);
const isInstitutionRoute = computed(() => route.path.startsWith('/institutions/'));
const isAboutRoute = computed(() => ['/about', '/leadership', '/partnerships'].includes(route.path));
const dropOpen = ref(false);
const aboutOpen = ref(false);
const mobileOpen = ref(false);

const navLinks = [
  { name: 'HOME', path: '/' },
  { name: 'CALENDAR', path: '/academic-calendar' },
  { name: 'BLOG', path: '/blog' },
];

const institutions = [
  { name: 'Jimmy Sekasi Business Institute', shortName: 'JSBI', path: '/institutions/jsbi', url: 'https://jsbi.vercel.app/', description: 'Business & Vocational Training' },
  { name: 'St. Andrew Kaggwa Gombe High School - Bujuuko', shortName: 'SAKGHS Bujuuko', path: '/institutions/sakghs-bujuuko', url: 'https://sakghs-bujuuko.vercel.app/', description: 'Advanced Secondary Education' },
  { name: 'St. Andrew Kaggwa Gombe High School - Kawaala', shortName: 'SAKGHS Kawaala', path: '/institutions/sakghs-kawaala', url: 'https://sakghs-kawaala.vercel.app/', description: 'Advanced Secondary Education' },
  { name: 'Gombe Junior School - Kampala', shortName: 'GJS Kampala', path: '/institutions/gjs-kampala', url: 'https://gjs-kikajjo.vercel.app/', description: 'Primary Education' },
  { name: 'Gombe Junior School - Gulu', shortName: 'GJS Gulu', path: '/institutions/gjs-gulu', url: 'https://gjs-gulu.vercel.app/', description: 'Primary Education' },
  { name: 'ScoobyDoo International School Uganda - Kampala', shortName: 'SISU Kampala', path: '/institutions/sisu-kampala', url: 'https://sisu-katale.vercel.app/', description: 'International Curriculum' },
  { name: 'ScoobyDoo International School Uganda - Gulu', shortName: 'SISU Gulu', path: '/institutions/sisu-gulu', url: 'https://sisu-gulu.vercel.app/', description: 'International Curriculum' },
  { name: 'International Education Pathways Program', shortName: 'IEPP', path: '/institutions/iepp', url: 'https://ipp-vert.vercel.app/', description: 'Global Study Pathways' },
];
</script>

<style scoped>
/* ── Main Header ── */
.ges-header {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  z-index: 100;
  background: var(--rescue-white, #fff);
  border-bottom: 1px solid var(--rescue-border, #E0E0E0);
  transition: box-shadow 0.3s ease;
}
.ges-header--scrolled {
  box-shadow: 0 2px 16px rgba(0,0,0,0.08);
}

/* ── Nav ── */
.ges-nav {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 1.5rem;
  max-width: 1280px;
  margin: 0 auto;
  height: 64px;
}

/* ── Brand ── */
.ges-brand {
  display: flex;
  align-items: center;
  text-decoration: none;
  flex-shrink: 0;
}
.ges-brand__logo {
  height: 48px;
  width: auto;
}

/* ── Desktop Nav Links ── */
.ges-nav__links {
  display: none;
  align-items: center;
  gap: 0;
}
@media (min-width: 1024px) {
  .ges-nav__links { display: flex; }
}
.ges-nav__link {
  position: relative;
  padding: 0.5rem 0.85rem;
  font-size: 0.8rem;
  font-weight: 700;
  color: var(--rescue-dark, #1A1A1A);
  text-decoration: none;
  background: none;
  border: none;
  cursor: pointer;
  font-family: inherit;
  display: flex;
  align-items: center;
  gap: 0.25rem;
  letter-spacing: 0.04em;
  transition: color 0.15s;
  white-space: nowrap;
}
.ges-nav__link:hover {
  color: var(--rescue-charcoal, #3D3D3D);
}
.ges-nav__link--active {
  color: var(--rescue-dark, #1A1A1A);
}
.ges-nav__link--active::after {
  content: '';
  position: absolute;
  bottom: 0;
  left: 0.85rem;
  right: 0.85rem;
  height: 3px;
  background: var(--rescue-yellow, #EFC131);
}

/* ── Nav CTA ── */
.ges-nav__cta {
  display: none;
}
@media (min-width: 1024px) {
  .ges-nav__cta { display: flex; align-items: center; margin-left: 1rem; }
}
.ges-nav__donate {
  display: inline-flex;
  align-items: center;
  gap: 0.6rem;
  padding: 0.55rem 1rem;
  background: var(--rescue-yellow, #EFC131);
  color: var(--rescue-dark, #1A1A1A);
  font-size: 0.9rem;
  font-weight: 800;
  text-decoration: none;
  border: 2px solid var(--rescue-yellow, #EFC131);
  cursor: pointer;
  transition: background 0.15s, transform 0.12s;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  border-radius: 2px;
  box-shadow: 0 6px 18px rgba(233,184,60,0.12);
}
.ges-nav__donate:hover {
  background: var(--rescue-yellow-hover, #D9AE28);
  transform: translateY(-1px);
}
.ges-nav__donate-text { display: inline-block; }

/* ── Dropdown ── */
.ges-dropdown {
  position: relative;
}
.ges-dropdown__trigger { white-space: nowrap; }
.ges-dropdown__arrow {
  transition: transform 0.2s;
}
.ges-dropdown__arrow--open {
  transform: rotate(180deg);
}
.ges-dropdown__menu {
  position: absolute;
  top: calc(100% + 8px);
  right: 0;
  background: var(--rescue-white, #fff);
  border: 1px solid var(--rescue-border, #E0E0E0);
  box-shadow: 0 8px 32px rgba(0,0,0,0.12);
  padding: 0.5rem;
  min-width: 300px;
  z-index: 200;
}
.ges-dropdown__menu--sm {
  min-width: 230px;
}
.ges-dropdown__item {
  display: flex;
  flex-direction: column;
  padding: 0.65rem 0.85rem;
  text-decoration: none;
  transition: background 0.15s;
  border-left: 3px solid transparent;
}
.ges-dropdown__item:hover {
  background: var(--rescue-grey-light, #F5F5F5);
  border-left-color: var(--rescue-yellow, #EFC131);
}
.ges-dropdown__item-name {
  font-size: 0.85rem;
  font-weight: 600;
  color: var(--rescue-dark, #1A1A1A);
}
.ges-dropdown__item-desc {
  font-size: 0.75rem;
  color: var(--rescue-text-secondary, #555);
  margin-top: 2px;
}

/* ── Hamburger ── */
.ges-hamburger {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  width: 24px;
  height: 18px;
  background: none;
  border: none;
  cursor: pointer;
  padding: 0;
}
@media (min-width: 1024px) {
  .ges-hamburger { display: none; }
}
.ges-hamburger__bar {
  display: block;
  width: 100%;
  height: 2.5px;
  background: var(--rescue-dark, #1A1A1A);
  border-radius: 2px;
  transition: transform 0.25s, opacity 0.25s;
  transform-origin: center;
}
.ges-hamburger__bar--open-1 { transform: translateY(8px) rotate(45deg); }
.ges-hamburger__bar--open-2 { opacity: 0; }
.ges-hamburger__bar--open-3 { transform: translateY(-8px) rotate(-45deg); }

/* ── Mobile Menu ── */
.ges-mobile-menu {
  display: flex;
  flex-direction: column;
  background: var(--rescue-white, #fff);
  border-top: 1px solid var(--rescue-border, #E0E0E0);
  padding: 1rem 1.5rem 1.5rem;
  max-height: 80vh;
  overflow-y: auto;
}
.ges-mobile-menu__link {
  padding: 0.7rem 0;
  font-size: 0.9rem;
  font-weight: 600;
  color: var(--rescue-dark, #1A1A1A);
  text-decoration: none;
  border-bottom: 1px solid var(--rescue-border, #E0E0E0);
  transition: color 0.15s;
  letter-spacing: 0.02em;
}
.ges-mobile-menu__link:hover { color: var(--rescue-charcoal, #3D3D3D); }
.ges-mobile-menu__link--sub {
  font-size: 0.85rem;
  font-weight: 500;
  color: var(--rescue-text-secondary, #555);
  padding-left: 1rem;
}
.ges-mobile-menu__divider {
  height: 1px;
  background: var(--rescue-border, #E0E0E0);
  margin: 0.75rem 0;
}
.ges-mobile-menu__section {
  font-size: 0.7rem;
  font-weight: 700;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color: var(--rescue-text-secondary, #555);
  padding: 0.5rem 0 0.25rem;
}
.ges-mobile-menu__cta {
  display: block;
  text-align: center;
  padding: 0.75rem;
  margin-top: 1rem;
  background: var(--rescue-yellow, #EFC131);
  color: var(--rescue-dark, #1A1A1A);
  font-size: 0.9rem;
  font-weight: 700;
  text-decoration: none;
  transition: background 0.2s;
}
.ges-mobile-menu__cta:hover {
  background: var(--rescue-yellow-hover, #D9AE28);
}

/* ── Transitions ── */
.dropdown-enter-active, .dropdown-leave-active {
  transition: opacity 0.15s, transform 0.15s;
}
.dropdown-enter-from, .dropdown-leave-to {
  opacity: 0;
  transform: translateY(-6px);
}
.mobile-menu-enter-active, .mobile-menu-leave-active {
  transition: opacity 0.2s, transform 0.2s;
}
.mobile-menu-enter-from, .mobile-menu-leave-to {
  opacity: 0;
  transform: translateY(-10px);
}
</style>

// src/components/layout/Header.jsx
import React, { useState, useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { LuMenu, LuX, LuChevronDown, LuSearch, LuSun, LuMoon } from 'react-icons/lu';

const Header = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [dropdownOpen, setDropdownOpen] = useState(null);
  const [scrolled, setScrolled] = useState(false);
  const [darkMode, setDarkMode] = useState(false);
  const location = useLocation();

  const institutions = [
    { name: 'St. Andrew Kaggwa Gombe High School - Kawaala', subdomain: 'sakghs-kawaala', path: '/institutions/sakghs-kawaala', description: 'Advanced Secondary Education' },
    { name: 'St. Andrew Kaggwa Gombe High School - Bujuuko', subdomain: 'sakghs-bujuuko', path: '/institutions/sakghs-bujuuko', description: 'Advanced Secondary Education' },
    { name: 'Scooby Doo International School Uganda (SISU) - Katale Campus', subdomain: 'sisu-katale', path: '/institutions/scooby-katale', description: 'International Curriculum' },
    { name: 'Scooby Doo International School Uganda (SISU) - Gulu Campus', subdomain: 'sisu-gulu', path: '/institutions/scooby-gulu', description: 'International Curriculum' },
    { name: 'Gombe Junior School - Kikajjo', subdomain: 'gjs-kikajjo', path: '/institutions/gjs-kikajjo', description: 'Primary & Lower Secondary' },
    { name: 'Gombe Junior School - Gulu', subdomain: 'gjs-gulu', path: '/institutions/gjs-gulu', description: 'Primary & Lower Secondary' },
    { name: 'Gombe Junior School - Boarding', subdomain: 'gjs-boarding', path: '/institutions/gjs-boarding', description: 'Primary & Lower Secondary' },
    { name: 'Jimmy Sekasi Business Institute', subdomain: 'jsbi', path: '/institutions/jsbi', description: 'Business & Entrepreneurship' },
  ];

  const navLinks = [
    { name: 'Home', path: '/' },
    { name: 'GES Life', path: '/ges-life' },
    { name: 'International Education Pathway Program', path: '/mentorship' },
    { name: 'GES Calendar', path: '/academic-calendar' },
  ];

  const aboutLinks = [
    { name: 'About Us', path: '/about', description: 'Learn about our vision and mission' },
    { name: 'School Management Committee', path: '/leadership', description: 'Meet the committee guiding our schools' },
  ];

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 20);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <motion.header
      initial={{ y: -100 }}
      animate={{ y: 0 }}
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-500 ease-in-out ${
        scrolled 
          ? 'bg-ges-navy/95 backdrop-blur-md shadow-lg py-2' 
          : 'bg-transparent py-6'
      }`}
    >
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center">
          {/* Logo */}
          <Link to="/" className="flex items-center space-x-3 group">
            <motion.img
              src="/logo.png"
              alt="GES Logo"
              className="h-12 w-auto group-hover:drop-shadow-lg transition-all duration-300"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            />
            <div className="hidden sm:block">
              <h1 className="text-xl font-bold text-white group-hover:text-ges-gold transition-colors">
                Gombe Education Services
              </h1>
              <p className={`text-xs font-medium tracking-wider ${scrolled ? 'text-ges-gold' : 'text-gray-300'}`}>
                EXCELLENCE SINCE 1995
              </p>
            </div>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden lg:flex items-center space-x-1">
            {navLinks.map((link) => (
              <Link
                key={link.path}
                to={link.path}
                className={`relative px-4 py-2 rounded-full text-sm font-medium transition-all duration-300 ${
                  location.pathname === link.path
                    ? 'text-ges-navy bg-ges-gold'
                    : 'text-white hover:bg-white/10'
                }`}
              >
                {link.name}
              </Link>
            ))}

            {/* About Dropdown */}
            <div
              className="relative ml-2"
              onMouseEnter={() => setDropdownOpen('about')}
              onMouseLeave={() => setDropdownOpen(null)}
            >
              <button className="flex items-center px-4 py-2 text-sm font-medium text-white hover:bg-white/10 rounded-full transition-all">
                About <LuChevronDown className="ml-1 w-4 h-4" />
              </button>
              <AnimatePresence>
                {dropdownOpen === 'about' && (
                  <motion.div
                    initial={{ opacity: 0, y: 10, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: 10, scale: 0.95 }}
                    className="absolute top-full right-0 mt-2 w-56 bg-white rounded-2xl shadow-2xl py-3 border border-gray-100 overflow-hidden z-[60]"
                  >
                    {aboutLinks.map((link, index) => (
                      <motion.div
                        key={link.path}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: index * 0.05 }}
                      >
                        <Link
                          to={link.path}
                          className="block px-6 py-3 hover:bg-ges-cream transition-colors group"
                        >
                          <div className="font-semibold text-ges-navy group-hover:text-ges-teal transition-colors">
                            {link.name}
                          </div>
                          <div className="text-xs text-ges-slate mt-1">
                            {link.description}
                          </div>
                        </Link>
                      </motion.div>
                    ))}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Institutions Dropdown */}
            <div
              className="relative ml-2"
              onMouseEnter={() => setDropdownOpen('institutions')}
              onMouseLeave={() => setDropdownOpen(null)}
            >
              <button className="flex items-center px-4 py-2 text-sm font-medium text-white hover:bg-white/10 rounded-full transition-all">
                Institutions <LuChevronDown className="ml-1 w-4 h-4" />
              </button>
              <AnimatePresence>
                {dropdownOpen === 'institutions' && (
                  <motion.div
                    initial={{ opacity: 0, y: 10, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: 10, scale: 0.95 }}
                    className="absolute top-full right-0 mt-2 w-80 bg-white rounded-2xl shadow-2xl py-3 border border-gray-100 overflow-hidden z-[60]"
                  >
                    {institutions.map((inst, index) => (
                      <motion.div
                        key={inst.subdomain}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: index * 0.05 }}
                      >
                        <Link
                          to={inst.path}
                          className="block px-6 py-3 hover:bg-ges-cream transition-colors group"
                        >
                          <div className="flex justify-between items-start">
                            <div>
                              <div className="font-semibold text-ges-navy group-hover:text-ges-teal transition-colors">
                                {inst.name}
                              </div>
                              <div className="text-xs text-ges-slate mt-1">
                                {inst.description}
                              </div>
                            </div>
                          </div>
                        </Link>
                      </motion.div>
                    ))}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="hidden lg:flex items-center space-x-3 ml-4">
            {/* Removed Apply Now button */}
          </div>

          {/* Mobile Menu Button */}
          <button
            onClick={() => setIsOpen(!isOpen)}
            className="lg:hidden p-2 text-white hover:bg-white/10 rounded-lg transition-colors"
          >
            {isOpen ? <LuX className="w-6 h-6" /> : <LuMenu className="w-6 h-6" />}
          </button>
        </div>

        {/* Mobile Menu */}
        <AnimatePresence>
          {isOpen && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="lg:hidden mt-4 bg-ges-navy/95 backdrop-blur-xl rounded-2xl border border-white/10 overflow-hidden"
            >
              <div className="p-4 space-y-2">
                {navLinks.map((link) => (
                  <Link
                    key={link.path}
                    to={link.path}
                    onClick={() => setIsOpen(false)}
                    className={`block px-4 py-3 rounded-xl transition-colors ${
                      location.pathname === link.path
                        ? 'bg-ges-gold text-ges-navy font-bold'
                        : 'text-white hover:bg-white/10'
                    }`}
                  >
                    {link.name}
                  </Link>
                ))}
                
                {/* About Dropdown for Mobile */}
                <div className="border-t border-white/10 pt-2 mt-2">
                  <button
                    onClick={() => setDropdownOpen(dropdownOpen === 'about-mobile' ? null : 'about-mobile')}
                    className="w-full text-left px-4 py-3 rounded-xl text-white hover:bg-white/10 transition-colors flex items-center justify-between"
                  >
                    <span>About</span>
                    <motion.div
                      animate={{ rotate: dropdownOpen === 'about-mobile' ? 180 : 0 }}
                      transition={{ duration: 0.2 }}
                    >
                      <LuChevronDown className="w-4 h-4" />
                    </motion.div>
                  </button>
                  <AnimatePresence>
                    {dropdownOpen === 'about-mobile' && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="pl-4 space-y-2"
                      >
                        {aboutLinks.map((link) => (
                          <Link
                            key={link.path}
                            to={link.path}
                            onClick={() => setIsOpen(false)}
                            className="block px-4 py-2 text-gray-300 hover:text-white hover:bg-white/5 rounded-lg text-sm"
                          >
                            {link.name}
                          </Link>
                        ))}
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
                
                <div className="h-px bg-white/10 my-4" />
                <div className="px-4 text-xs font-bold text-ges-gold uppercase tracking-wider mb-2">
                  Our Institutions
                </div>
                {institutions.map((inst) => (
                  <Link
                    key={inst.subdomain}
                    to={inst.path}
                    onClick={() => setIsOpen(false)}
                    className="block px-4 py-2 text-gray-300 hover:text-white hover:bg-white/5 rounded-lg text-sm"
                  >
                    {inst.name}
                  </Link>
                ))}
                <div className="pt-4 mt-4">
                  <motion.button
                    whileTap={{ scale: 0.95 }}
                    className="w-full bg-ges-gold text-ges-navy px-6 py-3 rounded-xl font-bold hover:bg-ges-teal hover:text-white transition-all duration-300"
                  >
                    Apply Now
                  </motion.button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </nav>
    </motion.header>
  );
};

export default Header;
